### ISSUE TITLE
Implement E2E integration tests

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/cmsis-toolbox#101]
Based on the [Test Migration Plan](https://github.com/Open-CMSIS-Pack/cbuild2cmake/wiki/cbuildgen-to-cbuild2cmake-test-migration), migrate/adapt/extend integration tests for covering `csolution.yml` projects, allowing the deprecation of devtools tests based on CPRJs.
- Evaluate test platforms suitable for this task.
- Ideally the test cases should run with all supported embedded toolchains (AC6, GCC, IAR and LLVM).
- The tests should give the same results, i.e. generate equivalent build artifacts, independently of the build manager backend (`cbuildgen` or the future `cbuild2cmake`).

**Comment by soumeh01** [comment]
Here is the ADR for the test framework evaluated/discussed and decided.
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/wiki/ADR-System-test-framework

**Comment by jkrech** [comment]
Any feedback from other participants in the project?

**Comment by soumeh01** [comment]
The initial implementation of the E2E test framework has been implemented.
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/test/RobotTests.md

**Comment by soumeh01** [comment]
In alignment with the scope of release 2.4.0, we have introduced the initial version of the E2E test framework.

**Comment by soumeh01** [comment]
New enhancements should be addressed under https://github.com/Open-CMSIS-Pack/devtools/issues/1508
