### ISSUE TITLE
Debug launch with multiproject solution

### ISSUE THREAD

**Issue by vescovd1** [Open-CMSIS-Pack/cmsis-toolbox#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

debugger launch only picks up first listed project from solution

### Expected Behavior

?? how to specify the launch project in laiunch.json or task.json

### Steps To Reproduce

When I generate a solution with a single project all works fine.
my launch.json looks like:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Arm Debug",
            "type": "arm-debug",
            "request": "launch",
            "serialNumber": "${command:device-manager.getSerialNumber}",
            "program": "${command:embedded-debug.getApplicationFile}",
            "cmsisPack": "${command:cmsis-csolution.getTargetPack}",
            "connectMode": "auto",
            "debugFrom": "main",
            "probe": "CMSIS-DAP",
            "programMode": "auto",
            "resetMode": "auto",
            "preLaunchTask": "Flash Device"
        }
    ]
}
and my task json looks like:
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "Build Context",
			"type": "cmsis-csolution.build",
			"solution": "${command:cmsis-csolution.getSolutionPath}",
			"rebuild": false,
			"problemMatcher": [],
			"group": {
				"kind": "build",
				"isDefault": true
			}
		},
        {
            "label": "Flash Device",
            "type": "arm-debugger.flash",
            "serialNumber": "${command:device-manager.getSerialNumber}",
            "program": "${command:arm-debugger.getApplicationFile}",
            "cmsisPack": "${command:device-manager.getDevicePack}",
            "problemMatcher": [],
            "dependsOn": "Build Context"
        }
	]
}

This works just fine for singe project solution.
If I have a solution that contains three projects, the first two listed are library build projects and the third is the actual app with dependicy of the previous two libraries. This also builds fine but debug launch seems to try to flash and debug only the first listed project (the library). 
I know I could hard code the absolute build output path in the launch.json's "program" node but that does not seem like the right thing to do.
Is there another way?

### Affected tools

- [X] cbuild
- [X] cbuild-gen
- [ ] cpackget
- [X] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [X] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

### Environment

Windows 10

**Comment by jreineckearm** [comment]
@vescovd1 , this issue is about the Arm Debugger extension from Arm which is outside the scope of Open-CMSIS-Pack.
Could you please open the issue there: https://github.com/ARM-software/vscode-arm-debugger/issues/new/choose ?
