### ISSUE TITLE
Can DFP be optional?

### ISSUE THREAD

**Issue by W-MINE** [Open-CMSIS-Pack/cmsis-toolbox#116]
Some vendors' DFPs have not been maintained for a long time, which can cause many problems.
For example:
- conflict with some components.
- AC6 not support. 

To solve these problems, some DFP source files must be manually modified.
Is it possible to put the modified DFP source files into “Source File Management”?

**Comment by jkrech** [comment]
The packs are owned and should be maintained by the pack vendor.
Have you tried to contact the vendor(s) and ask for an update? Probably they have not realized that this deliverable is significant for developers. If they have decided to stop the maintenance, then you need to ask them to "deprecate" the pack.

**Comment by W-MINE** [comment]
> The packs are owned and should be maintained by the pack vendor. Have you tried to contact the vendor(s) and ask for an update? Probably they have not realized that this deliverable is significant for developers. If they have decided to stop the maintenance, then you need to ask them to "deprecate" the pack.

Yes, packs are efficient for developers.
But when encountering problems with the packs, we cannot expect the vendor(s) to update quickly.
Here is a temporary workaround: 

1. The device's DFP package must be installed.
2. Do not specify any packages for the "packs" node.
3. Copy all files in the corresponding package to the project directory.
4. Specify the corresponding file in the *.cproject.yml or *.clayer.yml file.
5. Add the macro definitions required for the package.

Please refer to [RTX5-QuickStart-STM32F4](https://github.com/W-MINE/RTX5-QuickStart-STM32F4.git) for specific implementation.

**Comment by jkrech** [comment]
Please consider an alternative approach.
a) Extract/unzip/clone the latest pack version into a "development folder" of your choice
b) Make the required modification/fixes to the code
c) Edit the pdsc file and add a new `<release>` tag with an incremented version attribute at the top of the `<releases>` section
d) run `cpackget add <development folder>/<vendor>.<packname>.pdsc` (referencing you modified local pack repository's pdsc file)
Now this new pack version is accessible from any of your projects using that new pack version. As you have incremented the version number it will be picked by default if no specific version is specified in  your project.
This way you do not need to have local copies in all of your projects.

Let me know if you have any further questions.
