### ISSUE TITLE
CubeMX

### ISSUE THREAD

**Issue by FerdinandEn** [Open-CMSIS-Pack/cmsis-toolbox#125]
I have tried to create a CubeMX project (STM32F756) directly in VSCode. When I call the customized line in VSCode I only get the information that the exit code is 1.

> csolution CubeMX.csolution.yml run --generator CubeMX --context CubeMX.Debug+MyBoard

Do I need a new version of the F7 pack to be able to reproduce the procedure? 

I can't reproduce the example either, as I don't have the U585I packs with the required version.

**Comment by jkrech** [comment]
@FerdinandEn , die you follow the steps in this [ReadMe](https://github.com/Open-CMSIS-Pack/csolution-examples/tree/main/CubeMX#cubemx-project)
Make sure you are using CMSIS-Toolbox 2.3.0 and you need to clone the pack-examples and register the pdsc files as local repositories, as described. This gives you access to STM32U585 DFP and BSP. The STM32F7xx_DFP does not support the global generator yet.

**Comment by FerdinandEn** [comment]
CMSIS Toolbox is 2.3.0

For the CubeMX-Example:
I did not install the packs with cpackget. I have now done that. I was able to execute the cpackget instructions successfully. The Packs are also entered as local repositories.

STM32U5xx_DFP::3,0,0-dev0
B_U585_IOTA2A_BSP::2.0.0-dev1

> csolution CubeMX.csolution.yml run --generator CubeMX --context CubeMX.Debug+MyBoard

now leads to the error

> error csolution: required pack: Keil::B-U585I-IOT02A_BSP@2.0.0-dev0 not installed

After change of CubeMX.cbuild-pack.yml to dev1 CubeMX opens. I was then able to carry out all further steps successfully.


I assume I need a new pack for the STM32F7 so I can do the same experiment. Is that correct?

**Comment by jkrech** [comment]
Thanks a lot for your feedback and the hint that the cbuild-pack.yml is locking the BSP to 2.0.0-dev0.
An alternative to "overriding" the cbuild-pack.yml is to add the option `--load latest` which will ensure that the latest installed packs will get used.

As you can see here: https://github.com/Open-CMSIS-Pack/pack-examples we do not currently have the STM32F7 pack in the works yet.

**Comment by FerdinandEn** [comment]
After successfully completing the steps for using CubeMX, I wanted to gain some more experience. When opening Software Components, I received the following error message:

![image](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/assets/21216218/38d09976-09ab-45e6-8392-6ce1301f165f)

I am trying to set up a new project with the board. At first I was able to enter all the settings in Software Components. However, I noticed that the dev packs were not used. After switching to the dev packs, I could no longer use Software Components

![image](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/assets/21216218/b2619764-0d15-4790-971a-b8a09c57c1bd)

---
I have another question:

If I convert a STM32 project with uVision and then to VS Code. Can I then open CubeMX directly and adjust the settings?

The following templates are used for CubeMX in uVision

FrameworkCubeMX_gpdsc.ftl
MX_Device_h.ftl

The templates are missing when opening CubeMX directly.

**Comment by jkrech** [comment]
The first problem you report, looks like an extension specific issue that should be reported here:
https://github.com/ARM-software/vscode-cmsis-csolution/issues
It looks like the pre-release pack versions are not considered by the component window.

On the second topic, we are in the process of moving away from gpdsc, replacing this with the global generator. In MDK uVision 5.40 we will start supporting the global generator. We will no longer rely on the above mentioned ftl file shipped as part of the STM32*_DFP packs. Instead the cbridge is handling the data/file conversion.
https://github.com/Open-CMSIS-Pack/generator-bridge.
At that point uvprojx projects converted to csolution shall be compatible.

**Comment by FerdinandEn** [comment]
Thanks for the information.
I have now found the problem with the display in **Software Components**. If you include the packages in the uVision Pack Installer (**File->Manage Local Repositories**) the error occurs. If you use **cpackget add** the problem does not occur.

**Comment by FerdinandEn** [comment]
I have now succeeded in creating a new project for the STM32U585AIIx. To do this, however, I had to make some changes in various yml files. If you are interested I can describe my approach.

**Comment by FerdinandEn** [comment]
Packs for STM32U5xx included with **cpackget add**

New Solution Project with (create a new solution)

Target Device: STM32U585AIIx
Project Name: CubeMX (to be able to use the entry of the commands directly from the example)
Solution Name: CubeMX

CubeMX.csolution.yml 
- change -> created for CMSIS-Toolbox@2.3.0
- change pack ->   Keil::STM32U5xx_DFP@>=3.0.0-dev

CubeMX.cbuild-pack.yml 
- delete resolved-pack ->   Keil::STM32U5xx_DFP@>=2.2.1

CubeMX.cproject.yml
- Delete Files, file: ./main.c
- Add an new c-file e.g dummy.c to keep Group entry
  Remark: if I use an extra folder (e.g. SRC), the entry is added as ..\SRC\dummy.c. I has to change it to ../SRC/dummy.c
- Delete **component Device:Startup**
- Add **component: Device:CubeMX**

Use csolution **CubeMX.csolution.yml list generators --verbose** to get registered Generators

CubeMX (Global Registered Generator)
  base-dir: STM32CubeMX/STM32U585AIIx
    context: CubeMX.Debug+STM32U585AIIx
    context: CubeMX.Release+STM32U585AIIx
	
Use **csolution CubeMX.csolution.yml run --generator CubeMX --context CubeMX.Debug+STM32U585AIIx**

-> CubeMX is started -> make settings -> generate code

Use **cbuild CubeMX.csolution.yml --update-rte**

info cbuild: build finished successfully!

Now new pack components can be selected, e.g. RTOS2 e.g. Keil RTX5
- do not include startup, this is done be CubeMX -> ignore validation warning
- do not forget to change NVIC-setting in CubeMX
  **csolution CubeMX.csolution.yml run --generator CubeMX --context CubeMX.Debug+STM32U585AIIx**
  - Disable code generation for Systick, SVC and PendSV

 Use **cbuild CubeMX.csolution.yml --update-rte**

info cbuild: build finished successfully!

Unfortunately, I don't have a board to test the program

**Comment by jkrech** [comment]
With the recently released version of the CMSIS-Solution VSCode Extension and the new major versions of the [STM32 BSPs and DFPs ](https://github.com/OPen-CMSIS-Pack/#stm32-packs-with-generator-support) the generator integration should work fluently. For further documentation see: https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/CubeMX.md
For any further feedback, please open a new issue.
