### ISSUE TITLE
[Bug]: Doc broken URL link to "Linker Script Files"

### ISSUE THREAD

**Issue by chentang16** [Open-CMSIS-Pack/cmsis-toolbox#126]
### Current Behavior

Broken URL link to "Linker Script Files" on https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/build-overview.md#overview-of-operation
![2024-05-13_10-30-02](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/assets/18185016/6a153d10-dc90-4988-92b7-4f8467ff7831)

**Comment by jkrech** [comment]
linker script information moved from separate md file https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/Linker-Script-Management.md#automatic-linker-script-generation
to the build overview md file:  https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/build-overview.md#automatic-linker-script-generation

**Comment by soumeh01** [comment]
Fixed in https://github.com/Open-CMSIS-Pack/cmsis-toolbox/pull/127
@chentang16 This update resolves the concern you raised. Are you satisfied with closing the issue?
