### ISSUE TITLE
[Bug]: specification for executes doesn't specify command working directory

### ISSUE THREAD

**Issue by EaselinkBachmann** [Open-CMSIS-Pack/cmsis-toolbox#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current specification for the `executes:` node does not specify the working directory in which the provided command is invoked.

Since paths in a `.cproject.yml` are usually relative to the project directory the naive assumption is that the command is run in the project directory. However, the command is actually run in the intermediate directory in the current implementation in `cbuild2cmake`.

This can be worked around by creating relative paths to scripts (such as `../project/scripts/script.py` instead of just `scripts/script.py`) but this means hard-coding the path from the intermediate directory to the project directory. ~~The Access Sequences `$SolutionDir()$` and `$ProjectDir()$` could help, but those don't seem to be implemented in `cbuild2cmake` yet as of cmsis-toolbox 2.4.0~~ (found the implementation in `csolution`, that works, my bad).

Additionally, if `executes:` support is ever added to `cbuildgen` as well this would result in a different relative path due to the additional levels in the directory tree (`../../../project/scripts/script.py` due to `tmp/project/context/` instead of `tmp/`)

### Expected Behavior

The specification for `executes:` should specify the working directory the command runs in (or potentially allow the user to override it). IMO this working directory should by default be the project directory for project-level `executes:` and the solution directory for solution-level `executes:`.

### Steps To Reproduce

1. Create a solution and project with the following project-level `executes:` node:

```
    - execute: Show working directory
      run: echo WORKING DIRECTORY is $$PWD
      always:
```

2. Observe how it prints `WORKING DIRECTORY is <SOLUTION_DIR>/tmp`

### Affected tools

- [X] cbuild
- [ ] cbuild-gen
- [ ] cpackget
- [ ] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [ ] Windows amd64
- [ ] Windows arm64
- [X] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

### Environment

- reproducible on Arch Linux, Ubuntu 22.04, Ubuntu 24.04, using `vcpkg` artifacts and GitHub releases.

**Comment by brondani** [comment]
@EaselinkBachmann As written in the [`executes` documentation](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#executes) the nodes `input` and `output` accept access sequences.
Scripts and other files used in `execute` `run` should be listed among the `input` files, otherwise changes in such files won't automatically trigger a re-run as it is normally expected.

In your example I would recommend to follow this pattern:
```
executes:
  - execute: Run my script
    run: python $input(0)$
    input:
      - $ProjectDir()$/scripts/script.py
```

In such case there is no need to rely on the working directory location, which is not in the specification and therefore it has an implementation-defined behaviour.

**Comment by EaselinkBachmann** [comment]
Thanks for the clarification. I didn't know the `$input(N)$` syntax existed. Is there documentation on what extra parameters these access sequences can get. The documentation doesn't list the indexing syntax you showed at least.

Of course, the`executes:` feature is still experimental, so that's probably the reason why the documentation is still incomplete. Thank you for the clarification.

**Comment by brondani** [comment]
Yes, sorry for the lack of documentation, it seems the update was not yet merged, you can find it in @ReinhardKeil's branch: 
https://github.com/ReinhardKeil/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#executes
In the `cbuild2cmake` test data you can find an example that uses them:
https://github.com/Open-CMSIS-Pack/cbuild2cmake/tree/main/test/data/solutions/executes

**Comment by EaselinkBachmann** [comment]
Closing this as not-a-bug, since the working directory is intentionally unspecified.
