### ISSUE TITLE
Documentation: invalid YML input format for section 'solution: projects: - project:'

### ISSUE THREAD

**Issue by VladimirUmek** [Open-CMSIS-Pack/cmsis-toolbox#137]
### Current Behavior

The description of section 'solution: projects:'
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/5e02e850f2efa0bc2f4e2eb74cb3fad86132bd47/docs/YML-Input-Format.md?plain=1#L1532-L1550

does not match to what is allowed in the schema file (see the link below):
https://github.com/Open-CMSIS-Pack/devtools/blob/6b68c4980b9fe5ff99309a3ab1ad5cc0f550b57b/tools/projmgr/schemas/common.schema.json#L410-L426

### Expected Behavior

Mentioned section should be reviewed and cleaned up.

**Comment by brondani** [comment]
@jkrech Not only under the `setup` node, also the `project` node itself in `*.cproject.yml` accept several properties: [schema](https://github.com/Open-CMSIS-Pack/devtools/blob/tools/projmgr/2.4.0/tools/projmgr/schemas/common.schema.json#L834-L867) and [documentation](
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/2.4.0/docs/YML-Input-Format.md#project).

Just to make it clear, the `project` nodes that come under `projects` in `*.csolution.yml` are those that allow only `for-context` and `not-for-context`.

**Comment by jkrech** [comment]
This needs to be clarified in the documentation.

csolution.yml:
```
solution:
  projects: 
    project: ...
```
versus

cproject.yml:
```
project:
  ...
  setups:
    setup:
