### ISSUE TITLE
Documentation: add-path-asm element misspelled as add-asm-path in the YML input format

### ISSUE THREAD

**Issue by VladimirUmek** [Open-CMSIS-Pack/cmsis-toolbox#160]
### Current Behavior

Invalid element [add-asm-path](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#add-asm-path) exists in the CMSIS Solution Project File Format documentation.

### Expected Behavior

It should be replaced with [add-path-asm](https://github.com/Open-CMSIS-Pack/devtools/issues/607).

The schema contains correct element name, [see ProjectDescType](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/schemas/common.schema.json#L854).

**Comment by ReinhardKeil** [comment]
Done https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md
