### ISSUE TITLE
[Blocker]:  Arm compiler  6.16.2 (Fusa) uvproj  not working

### ISSUE THREAD

**Issue by dimaNovodes** [Open-CMSIS-Pack/cmsis-toolbox#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Unusable feature

uv2csolution
cbuild
vcpkg-configuration

### Current Behavior

Example Blinky project that compiles in keil uvision using 6.16.2 (Fusa) does not compile in VS code.

Some warnings show, and compiler mismatch in config.

> cbuild c:\Users\XXXXX\Documents\Blinky\Blinky.csolution.yml --update-rte --packs --context Blinky+STM32L476_Flash
spawn cbuild ENOENT

Warnings:
	Fix compiler version (6.16.2, 6.16.2) is configured in the uVision project.
	However 6.19.0, the earliest version available through vcpkg,
	is specified in the generated vcpkg-configuration.json and csolution file.
	
	
	{
	"registries": [
		{
		"kind": "artifact",
		"location": "https://artifacts.tools.arm.com/vcpkg-registry",
		"name": "arm"
		}
	],
	"requires": {
		"arm:tools/kitware/cmake": "^3.25.2",
		"arm:tools/ninja-build/ninja": "^1.10.2",
		"arm:compilers/arm/armclang": "6.19.0",		
		"arm:tools/open-cmsis-pack/cmsis-toolbox": "^2.3.0"
	}
}

### Expected Behavior

documents says should work:

![image](https://github.com/user-attachments/assets/30eea568-8c00-419b-8c04-7650f8aacb8b)

[Arm Compiler for Embedded](https://developer.arm.com/tools-and-software/embedded/arm-compiler/downloads/version-6) version 6.18.0 or higher

Arm FuSa Compiler for Embedded version 6.16.2 or higher is also supported

### Steps To Reproduce

1. Download 'Blinky' project to one of STM NUCLEO devices.
2. In Keil uvision, set compiler to 6.16.2 Fusa, and compile to update the uvproj file.
3. Go to VS code arm plugin , and try to convert in CMSIS screen the uvrpoj file.
4. Get bunch of errors.

### Affected tools

- [X] cbuild
- [ ] cbuild2cmake
- [ ] cpackget
- [X] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [X] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

### Environment

Windows 11

**Comment by jkrech** [comment]
While Arm Compiler for Embedded 6.16.2 is supported by CMSIS-Toolbox this compiler version can not be downloaded and registered using the VSCode Arm Environment Manager. 
Assuming you have installed version 6.16.2 in your Keil Installation already:
e.g. c:\Keil_v5\ARM\ARMClang_6_16_2\...
you need to set the TOOLCHAIN environment variable following instructions from here: https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/installation.md#compiler-toolchains

```
set AC6_TOOLCHAIN_6_16_2=c:\Keil_v5\ARM\ARMClang_6_16_2\bin
```

**Comment by jkrech** [comment]
Needs Arm internal investigation whether FuSa compiler versions will be distributed via `artifacts.tools.arm.com` in the future.
