### ISSUE TITLE
[Blocker]: Modify language standards

### ISSUE THREAD

**Issue by flair0626** [Open-CMSIS-Pack/cmsis-toolbox#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Unusable feature

Modify language standards

### Current Behavior

.cbuild.yml
   misc:
    ASM:
      - -masm=auto
    C:
      - -std=gnu11
      - -Wno-macro-redefined
      - -Wno-pragma-pack
      - -Wno-parentheses-equality
      - -Wno-license-management
      - -std=gnu17

### Expected Behavior

.cbuild.yml
   misc:
    ASM:
      - -masm=auto
    C:
      - -std=gnu17
      - -Wno-macro-redefined
      - -Wno-pragma-pack
      - -Wno-parentheses-equality
      - -Wno-license-management

### Steps To Reproduce

Add in. cpoject.yml
    setups:
    - setup: Options for Release
      misc:
        - C:
            - -std=gnu17

### Affected tools

- [ ] cbuild
- [ ] cbuild2cmake
- [ ] cpackget
- [X] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [X] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

**Comment by brondani** [comment]
@flair0626 Are you using the global [`cdefault`](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/2.6.0/docs/YML-Input-Format.md#cdefault) or setting [`misc`](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/2.6.0/docs/YML-Input-Format.md#misc) options in other places in your solution?

Please note:
- in the global [`cdefault.yml`](https://github.com/Open-CMSIS-Pack/devtools/blob/tools/projmgr/2.6.0/tools/projmgr/templates/cdefault.yml) several `misc` options are set.
- `misc` options are [additive](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/2.6.0/docs/YML-Input-Format.md#translation-control).

If the global cdefault options are not suitable to your solution you should use your local options instead.

**Comment by jkrech** [comment]
@flair0626 can you please comment, whether Daniel's suggestions above helped you to resolve  your problem?

**Comment by flair0626** [comment]
It has been resolved. Thank you
