### ISSUE TITLE
[question]: cmsis-toolbox-windows-amd64\bin\csolution.exe --version returns 2.6.0 instead of 2.6.1

### ISSUE THREAD

**Issue by LorenaLazarNXP** [Open-CMSIS-Pack/cmsis-toolbox#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

cmsis-toolbox-windows-amd64\bin\csolution.exe --version returns 2.6.0 instead of 2.6.1. Checked only on Windows so far

### Expected Behavior

cmsis-toolbox-windows-amd64\bin\csolution.exe --version should return 2.6.1

### Affected tools

- [ ] cbuild
- [ ] cbuild2cmake
- [ ] cpackget
- [X] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [X] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

**Comment by jkrech** [comment]
Note that CMSIS-Toolbox 2.6.1 is a patch release with only a few tools being updated.
See https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/tag/2.6.1
Patched Tools:
    [Build Invocation Utility 2.6.1](https://github.com/Open-CMSIS-Pack/cbuild/releases/tag/v2.6.1)
    [Generator Bridge 0.9.12](https://github.com/Open-CMSIS-Pack/generator-bridge/releases/tag/v0.9.12)
    [CMake File Generator 0.9.4](https://github.com/Open-CMSIS-Pack/cbuild2cmake/releases/tag/v0.9.4)

**Comment by ReinhardKeil** [comment]
The problems fixed are listed here https://github.com/orgs/Open-CMSIS-Pack/projects/15

**Comment by LorenaLazarNXP** [comment]
OK, got it, thank you for the quick answer.  Is there a way to retrieve the patch/release version from the archive file? Perhaps from a release notes document?

**Comment by jkrech** [comment]
I have created this enhancement ticket: https://github.com/Open-CMSIS-Pack/cmsis-toolbox/issues/184

**Comment by jkrech** [comment]
Note: `created-for: CMSIS-Toolbox@2.6.0` must be used, as csolution version remains 2.6.0 in the patch release CMSIS-Toolbox version  2.6.1.
