### ISSUE TITLE
Suggestion: perform index update when "cbuild --packs" is called

### ISSUE THREAD

**Issue by vovamarch** [Open-CMSIS-Pack/cmsis-toolbox#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When `cbuild [setup]` is called with `--packs`, it is expected that the missing packs get downloaded and installed. However, if the pack index is not uptodate and doesn't contain information about a recently released pack that is now required by the project. there is a failure reported that this pack cannot be found. Current approach is for the user to perform `cpackget update-index` before cbuild.

The issue is likely to appear in local CLI environments and in CI workflows with cached pack downloads, if no periodic index update is implemented, and especially at times of new pack releases.

### Expected Behavior

--packs option already sets an expectation that packs required by the project will be downloaded from the web. This could be combined with the index update for at least the packs used in the project saving an extra step for users. 

### Affected tools

- [X] cbuild
- [ ] cbuild2cmake
- [ ] cpackget
- [ ] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [ ] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

### Environment

Any

**Comment by jkrech** [comment]
This is covered here:
https://github.com/Open-CMSIS-Pack/cpackget/issues/355


Workaround: In a CI system that expects to work with latest packs the scripts should contain the `cpackget update-index` during setup.
