### ISSUE TITLE
[Bug]: cgen file not generated with CubeMX for GCC

### ISSUE THREAD

**Issue by francovaro** [Open-CMSIS-Pack/cmsis-toolbox#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm testing cmsis-toolbox with a Nucelo F446RE board, see the repo here: https://github.com/francovaro/example-csolution-stm32 
I have created the solution using the wizardm then I tried to generate the the project files following this instruction: https://github.com/Open-CMSIS-Pack/csolution-examples/tree/main/CubeMX#using-gcc-compiler

But when I compile I get this error:

```
Nucleo_STM32F4466/stm32.cgen.yml - error csolution: cgen file was not found, run generator 'CubeMX' for context 'stm32.Debug+Nucleo_STM32F446ext 'stm32.Debug+Nucleo_STM32F4466'
error csolution: processing context 'stm32.Debug+Nucleo_STM32F4466' failed 
```

If I select MDK-ARM the file is generated correctly.

### Expected Behavior

cgen.yml file is generated fot STM32CubeIDE

### Steps To Reproduce

1. Create solution for STM32F4, using CubeMX template
2. Run CubeMX generator
3. Select STM32CubeIDE as toolchain
4. compile

### Affected tools

- [X] cbuild
- [ ] cbuild2cmake
- [ ] cpackget
- [ ] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [ ] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

### Environment

Test on Win amd64

**Comment by DavidLesnjak** [comment]
Can you check if you disabled the "Generate Under Root" option in STM32CubeMX after selecting the toolchain/IDE "STM32CubeIDE"?
