### ISSUE TITLE
[Enhancement] Build could show resulting program size at the end of the build process 

### ISSUE THREAD

**Issue by MiloradCvjetkovic** [Open-CMSIS-Pack/cmsis-toolbox#218]
Currently `cbuild` result looks like below:
```
Finished: 0 information, 2 warning and 0 error messages.

+------------------------------------------------------------
Build summary: 1 succeeded, 0 failed - Time Elapsed: 00:00:12
+============================================================
Completed: cbuild succeed with exit code 0
Build complete
```

But very often also important information is resulting program size, for example in `uVision` this was shown as below:
```
Program Size: Code=25344 RO-data=864 RW-data=12 ZI-data=6552  
".\Objects\Fault_S.axf" - 0 Error(s), 0 Warning(s).
Build Time Elapsed:  00:00:04
```

It would be useful to see the program size instead of looking for that information in the generated `.map` file.

**Comment by MiloradCvjetkovic** [comment]
Thank you @brondani , 
I checked the example I worked on and it had custom local `cdefault.yml` which did not contain linker switch `--info summarysizes
` and that was the reason that I did not see the results.
Issue closed.

**Comment by ReinhardKeil** [comment]
Next version covers that.  Use the upcoming 2.7 release.  Hence closing this issue

**Comment by ReinhardKeil** [comment]
@MiloradCvjetkovic are you using the new `cdefault.yml` that comes with 2.7?

**Comment by MiloradCvjetkovic** [comment]
I must say I relied that our RefApp are designed to show program size, but that is not true.
Let me check that again.

**Comment by MiloradCvjetkovic** [comment]
Linker switch `- -Wl,-print-memory-usage` in the new `cdefault.yml` does indeed work.
Issue closed.
