### ISSUE TITLE
CMSIS Toolbox not reliably installed on Apple Silicon Macs

### ISSUE THREAD

**Issue by madchutney** [Open-CMSIS-Pack/cmsis-toolbox#27]
When installing the toolbox from the command line using vcpkg we had unreliable results on Apple Silicon Macs. In some environments the binary would be downloaded and in others it would not, we could not be sure why there is a difference in behaviour, but we believe it is related to the architecture and/or version of the Node being used.

However, we have found a simple solution, if `and x64` is removed from [the template](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/942f6f50d28bec40d7b958489994682a7b0daaba/.github/ctools.json.in#L43) and therefore the json manifest the tools can reliably be downloaded on a Mac with Apple Silicon and run under Rosetta.

When an Arm version of the tools is available then they can both be listed with the architecture, and Rosetta won’t be needed any longer.

**Comment by JonatanAntoni** [comment]
We can relax this condition until we have nativ arm builds for Mac.
I pushed an updated registry at https://github.com/Open-CMSIS-Pack/vcpkg-ce-registry/archive/refs/heads/arm_macs.zip. Can you please confirm that this change works as expected? If so, I'll accept this to become productive and change the template for upcoming releases.

**Comment by jkrech** [comment]
@madchutney the registry got updated according to your suggestion.
See: https://aka.ms/vcpkg-artifacts-cmsis

**Comment by madchutney** [comment]
Thanks, much appreciated.
