### ISSUE TITLE
Minimum version of macOS?

### ISSUE THREAD

**Issue by graeme-winter** [Open-CMSIS-Pack/cmsis-toolbox#31]
Just installed the toolbox on macOS big sur and `cpackget` works fine, but `csolution` is missing a symbol

```
silver-surfer-2 cmsis :) $ cpackget list
I: Using pack root: "/Users/graeme/.cache/arm/packs" (default mode - no specific CMSIS_PACK_ROOT chosen)
I: Listing installed packs
I: Microchip::SAMD51_DFP@3.6.120
silver-surfer-2 cmsis :) $ csolution list packs
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Users/graeme/C/cmsis/cmsis-toolbox-darwin-amd64/bin/csolution (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/graeme/C/cmsis/cmsis-toolbox-darwin-amd64/bin/csolution
Abort trap: 6
silver-surfer-2 cmsis :( $ which csolution
/Users/graeme/C/cmsis/cmsis-toolbox-darwin-amd64/bin/csolution
silver-surfer-2 cmsis :) $ otool -L $(which csolution)
/Users/graeme/C/cmsis/cmsis-toolbox-darwin-amd64/bin/csolution:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.36.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
```

Is my system no longer supported? It is fairly up to date (though I agree on patch releases as newest macOS does not support this machine). I could not find the minimum version anywhere...

**Comment by graeme-winter** [comment]
Oh, wait, I should have answered my own question:

```
(which was built for Mac OS X 12.6)
```

however I suspect that this is an excessively recent version, and probably whoever built could have assigned a more modest minimum macOS version, as applied to the other binaries.

**Comment by jkrech** [comment]
Thanks a lot for sharing the feedback.
We have tools programmed in GO (e.g. cbuild, cpackget) and C++ (e.g. csolution, cbuildgen, etc.).
This is the reason for seeing differences between the tools in the toolbox.

A colleague of mine thinks that for macOS we need to look into setting "minimum deployment target version" explicitly: 
see https://cmake.org/cmake/help/latest/envvar/MACOSX_DEPLOYMENT_TARGET.html
We also need to document that version then.

**Comment by graeme-winter** [comment]
@jkrech thanks for picking this up - yes, precisely that - we do this for software we deliver for work, written in C++ / Python - I think by default it uses the version on your build machine as the base. Setting `MACOSX_DEPLOYMENT_TARGET=11.7` would seem reasonable as Big Sur is still getting security paches...

**Comment by JonatanAntoni** [comment]
Hi @graeme-winter,

We can add this to the CMakeLists.txt of devtools which are written in C++.
Does a similar issue apply to the tools written in Go?

If I am correct, we need to set compiler flag `-mmacosx-version-min=11.7` to achieve Big Sur compatibility. This can be done for Go utilities as well. Could you check if binaries work for you once I provide the pull-requests with the required chanes?

Cheers,
Jonatan

**Comment by graeme-winter** [comment]
> @graeme-winter, please find a pre-commit build with the proposed changes at https://github.com/Open-CMSIS-Pack/devtools/actions/runs/4690911613. You can download the projmgr-darwin-amd64 or -arm64 artifact that matches your system. You should receive a zip archive with a csolution binary containing the change. Please let us know if this fixes your issues.
> 
> You reported that you don't have issues with cpackget. What about cbuild? Both tools are written in Go and would require a different solution. I was not yet able to understand how to instruct the Go build system to use `-mmacosx-version-min=11.7`.

OK, it seems only `cpackget` actually works - 

```
silver-surfer-2 bin :) $ for f in *; do ./$f > /dev/null 2>&1 ; echo $f $?; done 
cbuild 255
Abort trap: 6
cbuildgen 134
cpackget 0
Abort trap: 6
csolution 134
Abort trap: 6
packchk 134
Abort trap: 6
svdconv 134
```

After a quick `unzip / chmod / xattr -r -d com.apple.quarantine` the binary runs correctly 

```
CMSIS Project Manager 0.0.0+g55b3e7e (C) 2023 Arm Ltd. and Contributors

Usage:
  csolution [-V] [--version] [-h] [--help]
            <command> [<arg>] [OPTIONS...]

 Commands:
   list packs            Print list of used packs from the pack repository
   list boards           Print list of available board names
   list devices          Print list of available device names
   list components       Print list of available components
   list dependencies     Print list of unresolved project dependencies
   list contexts         Print list of contexts in a csolution.yml
   list generators       Print list of code generators of a given context
   list layers           Print list of available, referenced and compatible layers
   list toolchains       Print list of supported toolchains
   convert               Convert *.csolution.yml input file in *.cprj files
   run                   Run code generator

 Options:
   -s, --solution arg    Input csolution.yml file
   -c, --context arg     Input context name <cproject>[.<build-type>][+<target-type>]
   -f, --filter arg      Filter words
   -g, --generator arg   Code generator identifier
   -m, --missing         List only required packs that are missing in the pack repository
   -l, --load arg        Set policy for packs loading [latest|all|required]
   -L, --clayer-path arg Set search path for external clayers
   -e, --export arg      Set suffix for exporting <context><suffix>.cprj retaining only specified versions
   -t, --toolchain arg   Selection of the toolchain used in the project optionally with version
   -n, --no-check-schema Skip schema check
   -U, --no-update-rte   Skip creation of RTE directory and files
   -v, --verbose         Enable verbose messages
   -d, --debug           Enable debug messages
   -o, --output arg      Output directory

Use 'csolution <command> -h' for more information about a command.
```

I think you can achieve the same thing with environment variables, which may work with the go based tools.

**Comment by jkrech** [comment]
To be very honest I don't really get the purpose yet.
I just came across the `vtool` which allows you to change the version in a copy of the binary.
Would you fancy trying whether this would work for you on the existing binaries (1.5.0) ?  See man pages for detailed instructions.

**Comment by graeme-winter** [comment]
> To be very honest I don't really get the purpose yet. I just came across the `vtool` which allows you to change the version in a copy of the binary. Would you fancy trying whether this would work for you on the existing binaries (1.5.0) ? See man pages for detailed instructions.

I had a look, and this _is_ a useful tool - 

```
silver-surfer bin :( $ vtool -show-build csolution 
csolution:
Load command 10
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform MACOS
    minos 12.6
      sdk 13.1
   ntools 1
     tool LD
  version 820.1
```

but the minimum OS / SDK requirement means that there are compiled in dependencies which are not available in earlier OS versions as was originally reported

```
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Users/graeme/C/cmsis/cmsis-toolbox-darwin-amd64/bin/./csolution (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/graeme/C/cmsis/cmsis-toolbox-darwin-amd64/bin/./csolution
Abort trap: 6
```

Simply stripping out the build flag won't change that

**Comment by graeme-winter** [comment]
For comparison, the test binary from yesterday 

```
silver-surfer test :( $ vtool -show-build csolution 
csolution:
Load command 10
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform MACOS
    minos 11.7
      sdk 13.1
   ntools 1
     tool LD
  version 820.1
```

**Comment by brondani** [comment]
@graeme-winter It's expected that `cbuild` will return 255 if you run it without valid arguments.
Running `vtool` over `cbuild` 1.5.0 shows it has `minos` 10.13:
```
vtool -show-build ./cbuild
./cbuild:
Load command 4
      cmd LC_BUILD_VERSION
  cmdsize 24
 platform MACOS
    minos 10.13
      sdk 10.13
   ntools 0
```
Could you please double check whether `cbuild` 1.5.0 has dependencies issues in your environment? Thanks!

**Comment by graeme-winter** [comment]
@brondani yes, you are right 

```
silver-surfer-2 bin :) $ ./cbuild
cbuild: Build Invocation 1.5.0 (C) 2023 Arm Ltd. and Contributors

Usage:
  cbuild [command] <project.cprj | csolution.yml> [flags]

Available Commands:
  help        Help about any command
  list        List information

Flags:
  -c, --clean                  Remove intermediate and output directories
      --configuration string   Input configuration name e.g. [.buildType][+targetType]
      --context string         Input context name e.g. project.buildType+targetType
  -d, --debug                  Enable debug messages
  -g, --generator string       Select build system generator (default "Ninja")
  -h, --help                   Print usage
  -i, --intdir string          Set directory for intermediate files
  -j, --jobs int               Number of job slots for parallel execution
      --load string            Set policy for packs loading [latest|all|required]
  -l, --log string             Save output messages in a log file
  -o, --outdir string          Set directory for output binary files
  -O, --output string          Set directory for all output files
  -p, --packs                  Download missing software packs with cpackget
  -q, --quiet                  Suppress output messages except build invocations
  -r, --rebuild                Remove intermediate and output directories and rebuild
  -s, --schema                 Validate project input file(s) against schema
  -t, --target string          Optional CMake target name
  -u, --update string          Generate *.cprj file for reproducing current build
      --update-rte             Update the RTE directory and files
  -v, --verbose                Enable verbose messages from toolchain builds
  -V, --version                Print version

Use "cbuild [command] --help" for more information about a command.
error cbuild: invalid arguments
```

It has no dependency issues

**Comment by jkrech** [comment]
Version 1.6.0 is available now:
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/tag/1.6.0
Please check whether all the utilities run successfully on your MacOS 11.7 now.

**Comment by graeme-winter** [comment]
Close but we don't appear to be there yet

```
cbuild
cbuildgen
cpackget
csolution
```

all good but

```
silver-surfer-2 bin :) $ ./packchk 
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Users/graeme/C/cmsis/cmsis-toolbox-darwin-amd64/bin/./packchk (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/graeme/C/cmsis/cmsis-toolbox-darwin-amd64/bin/./packchk
Abort trap: 6
silver-surfer-2 bin :) $ ./svdconv 
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Users/graeme/C/cmsis/cmsis-toolbox-darwin-amd64/bin/./svdconv (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/graeme/C/cmsis/cmsis-toolbox-darwin-amd64/bin/./svdconv
Abort trap: 6
```

not so...

**Comment by jkrech** [comment]
@graeme-winter - you are right. The versions of svdconv and packchk were not update in CMSIS-Toolbox 1.6.0 as they showed a regression, but there is more recent individual releases available that you may want to check. Sorry for the inconvenience.
[svdconv](https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools%2Fsvdconv%2F3.3.45)
[packchk](https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools%2Fpackchk%2F1.3.99)
packchk currently siliently fails if it does not find the file `../etc/PACK.xsd` to do the schema check.
So in case you plan to update your cmsis-toolbox locally just make sure to add the PACK.xsd file to the etc folder.

**Comment by graeme-winter** [comment]
OK, great thank you - I now have a full set of tools up and running, next job is to figure out how to use them all. Shall I leave this open until you feel you've got the minimum versions documented / closed out? Appreciate the help with getting this fixed up, appreciate that macOS is an unusual platform for MCU development ;-)
