### ISSUE TITLE
Make available via Chocolatey package manager

### ISSUE THREAD

**Issue by Jonny-vb** [Open-CMSIS-Pack/cmsis-toolbox#6]
I'm keen to start using these tools more, but it would be nice to have them readily available via a package manager like chocolatey so that they are easily installable/upgradable. For instance I believe that the version shipped with the latest uVision release is already outdated.
Making them available through a package manager would make using these tools easier, especially in automated CI scenarios.
You should be able to set up your release process to automatically setup and push a package out to chocolatey to reduce the manual overhead of maintaining it also.

**Comment by jkrech** [comment]
Unfortunately there is many package managers today. Therefore we have opted for zip/tgz as well as a file with the hashsums and people can simply download, validate the checksum before extracting it, where they need it and then setup the environment variables and adapt the etc/<compiler>.<version>.mak files.

Please see github.com/Open-CMSIS-Pack/vcpkg-ce-registry/ for an expermient to using Microsoft vcpkg artifacts.

**Comment by Jonny-vb** [comment]
I feel like saying that there are too many choices so we're not going to do any seems like a strange approach. Package managers make dealing with dependencies much easier with CI. Any package manager you do support should probably be done so that it doesn't actually require steps from yourselves when setup either - it should be something that your CI just spits out.

I wouldn't mind if something else other than Chocolatey is used (I currently use it for fetching other dependencies in my CI setup, such as python and LLVM and it works great) - but a commitment to something would be nice.

**Comment by jkrech** [comment]
I think you have misinterpreted my comment:
Have you looked a vcpkg from Microsoft as I commented above, this is what we are currently supporting event though it has some shortcomings still in case you are not using default paths. 
Have you tried to run the selfextracting shell based installer. You would need to run a bash shell on Windows for that.
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/download/1.1.0/cmsis-toolbox.sh

The project is always open to contributions, therefore feel free to develop a solution and raise a PR.

**Comment by jkrech** [comment]
We have established the use of Microsoft vcpkg artifacts to download, install and activate the CMSIS-Toolbox releases.
See: github.com/OPen-CMSIS-Pack/vscode-get-started/
Even though this demonstrates the use within Visual Studio Code, vcpkg can be installed independently as well. 
See here:  https://devblogs.microsoft.com/cppblog/vcpkg-artifacts/#acquire-vcpkg for how to acquire vcpkg (without cloning the vcpkg github repo!).
