### ISSUE TITLE
cproject targeting toolchain AC6 with only a single legacy ASM assembler file does not link

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/cmsis-toolbox#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Unusable feature

The linked project can be converted successfully by [uv2csolution 1.0.0](https://artifacts.keil.arm.com/uv2csolution/1.0.0/) into a csolution formatted project. 
https://downloads.software.api.keil.arm.com/projects/flash-option-bytes-86968ef2.zip

This project targets Arm Compiler 6 (AC6) toolchain and only contains a single module using the AC5 assembler syntax for `armasm`. If only such a file exists, it seems that the linker does not create an axf file output but also not throws an error.

### Current Behavior

C:/workspaces/Nucleo_G747RE/tmp/FlashOptionBytes/STM32G4xxSBOPT
[1/2] Building AS_ARM object CMakeFiles\FlashOptionBytes.dir\C_\workspaces\Nucleo_G747RE\STM32G4xx_SB_OPT.o
Warning: A1950W: The legacy armasm assembler is deprecated. Consider using the armclang integrated assembler instead.
0 Errors, 1 Warning
[2/2] Linking AS_ARM executable C:\workspaces\Nucleo_G747RE\out\FlashOptionBytes\STM32G4xxSBOPT\FlashOptionBytes.axf
info cbuild: build finished successfully!

=> despite the last message no file FlashOptionBytes.axf got generated

### Expected Behavior

=> at least an error message - if this scenario (using legacy ASM only) is not supported
better:
=> FlashOptionBytes.axf gets generated by the linker step for a project that only has an armasm module.

### Steps To Reproduce

1. download project
2. unzip project
3. run `uv2csolution`
4. run `cbuild ...`

### Affected tools

- [ ] cbuild
- [X] cbuild-gen
- [ ] cpackget
- [ ] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [X] Windows amd64
- [X] Windows arm64
- [X] Linux amd64
- [X] Linux arm64
- [X] MacOS amd64
- [X] MacOS arm64

**Comment by jkrech** [comment]
We don't have a linker handling for the language of the assembly file, which is "AS_ARM" that we introduced just to cope with legacy projects.
A workaround could be something like this:

set(CMAKE_AS_ARM_LINK_EXECUTABLE "armlink <CMAKE_AS_ARM_LINK_FLAGS> <LINK_FLAGS> <LINK_LIBRARIES> <OBJECTS> -o <TARGET>")

@brondani  where (filename + line number) would this workaround need to be applied or is this being generated?

**Comment by brondani** [comment]
@jkrech The workaround can be appended to the `AC6.<version>.cmake` file.

**Comment by jkrech** [comment]
critical label removed due to provided workaround above.

**Comment by brondani** [comment]
Fixed in https://github.com/Open-CMSIS-Pack/devtools/pull/1101
