### ISSUE TITLE
[Bug]: language-cpp has no effect

### ISSUE THREAD

**Issue by smartinou** [Open-CMSIS-Pack/cmsis-toolbox#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using key language-cpp in *.cproject.yml file, there is no matching compiler flag being generated for the specified value.

### Expected Behavior

For example, it is expected that specifying this in *.cproject.yml
`language-CPP: c++20`
... will produce:
`-std=c+=20`
... on the compiler command line. Yet this is not the case.
Workaround:
The only way I found to specify a c++ standard so far is using:  `target-types/misc/CPP/-std=c++20`

### Affected tools

- [ ] cbuild
- [ ] cbuild-gen
- [ ] cpackget
- [X] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [ ] Windows amd64
- [ ] Windows arm64
- [X] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

### Environment

- Ubuntu 22.04LTS

**Comment by brondani** [comment]
@smartinou Which toolchain are you using? Can you please provide a reproducer?
With the attached [GCC solution](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/files/12715889/language_cpp.zip), where the CPP language is set as this:
```
  language-CPP: c++20
```
When calling cbuild in debug mode:
```
cbuild language.csolution.yml -d
```
I see the following compiler command line:
```
Run Build Command(s): [...]
[1/2] [...] -std=c++20 [...] main.cpp
```

**Comment by smartinou** [comment]
Hi @brondani
I tried the attached [GCC solution](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/files/12715889/language_cpp.zip) in my env. GCC version is 12.3.1. Yet I can't manage to have it output the C++ standard at the compiler command line.

I've attached the generated .cprj file: it clearly shows the languageCPP option.
I've also attached the vs code task execution for building the project.

Let me know if I can be of any other help.
[project_and_output.zip](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/files/12720978/project_and_output.zip)

**Comment by brondani** [comment]
@smartinou Thanks for the attachments.
From the output it seems you are using the tools via `vcpkg` but you have also set the environment variable `CMSIS_COMPILER_ROOT` to a local installation which is maybe an older one:
```
debug cbuild: CMSIS_COMPILER_ROOT: /home/martin/opt/ctools/etc
```
Could you please unset `CMSIS_COMPILER_ROOT` and check whether it solves the issue?

**Comment by smartinou** [comment]
SOLVED: set env variables properly to use with vcpkg and Visual Studio Code extension

1. Removed `CMSIS_COMPILER_ROOT` from .bashrc
2. Started new shell. Confirmed env var not set.
3. Started vscode at workspace location within this new shell.
4. Activated vcpkg environment in the project.

Terminal output now shows default value for `CMSIS_COMPILER_ROOT`:

debug cbuild: CMSIS_COMPILER_ROOT: /home/martin/.vcpkg/artifacts/fd3d78d7/tools.open.cmsis.pack.cmsis.toolbox/2.1.0/etc

... and now I get to see c++20 as expected.

Please feel free to mark as INVALID, and thanks for all the help!
