### ISSUE TITLE
[Bug]: Mismatch between documentation and schema for `context-map` node

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/cmsis-toolbox#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Following the documentation: https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#context-map
a context-map lists `- context: myproject.debug+target` key value items whereas the schema expects values only 
```
context-map:
  - myproject.debug+target
```

### Expected Behavior

I personally are more used to the `key: <value>` pairs being used.

### Affected tools

- [ ] cbuild
- [ ] cbuild-gen
- [ ] cpackget
- [X] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [X] Windows amd64
- [X] Windows arm64
- [X] Linux amd64
- [X] Linux arm64
- [X] MacOS amd64
- [X] MacOS arm64

**Comment by brondani** [comment]
Lists of items that don't have extra properties, such as `add-paths`, `del-paths` and `undefines` are expected as normal yml sequences. See [schema](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/schemas/common.schema.json#L235-L254).

**Comment by ReinhardKeil** [comment]
I will fix documentation.
