### ISSUE TITLE
[Bug]: Incorrect description for default value of outdir

### ISSUE THREAD

**Issue by Hoohaha** [Open-CMSIS-Pack/cmsis-toolbox#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#output-dirs
Doc said the default settings for outdir is 
```
outdir:  $SolutionDir()$/out/$TargetType$
```

But when specifying the `--output /my/outputpath/` in cbuild command line.
the generated is in `/my/outputpath/out/$Project$/$TargetType$`/$BuildType$, not in `$SolutionDir()$`.

So what's the right default outdir?

### Affected tools

- [X] cbuild
- [ ] cbuild-gen
- [ ] cpackget
- [ ] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [X] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

**Comment by brondani** [comment]
As stated in the [mentioned document](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#output-dirs:~:text=Use%20command%20line%20options%20of%20the%20cbuild%20tool%20to%20redirect%20the%20absolute%20path%20for%20this%20working%20directory.):
>Use command line options of the cbuild tool to redirect the absolute path for this working directory.

It means the command line option `--output` takes precedence over other settings.
