### ISSUE TITLE
[Bug]: macOS-arm64 cpackget binary is not notarized

### ISSUE THREAD

**Issue by sandeepmistry** [Open-CMSIS-Pack/cmsis-toolbox#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[macOS-arm64](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/download/2.2.1/cmsis-toolbox-darwin-arm64.tar.gz) `cpackget ` binary is not notarized.

When running the following dialog appears:
<img width="372" alt="Screenshot 2023-12-20 at 9 30 02 AM" src="https://github.com/Open-CMSIS-Pack/cmsis-toolbox/assets/1163840/75a5ee41-388c-477d-8b32-28121ae2e0b5">

`spctl` yields:
```
% spctl -a -vvv -t install ~/Downloads/cmsis-toolbox-darwin-amd64/bin/cpackget
/Users/sanmis01/Downloads/cmsis-toolbox-darwin-amd64/bin/cpackget: rejected
source=no usable signature
```

I ran `spctl` on the other binaries as well:
```
spctl -a -vvv -t install ~/Downloads/cmsis-toolbox-darwin-amd64/bin/*
/Users/sanmis01/Downloads/cmsis-toolbox-darwin-amd64/bin/cbridge: rejected
source=no usable signature
/Users/sanmis01/Downloads/cmsis-toolbox-darwin-amd64/bin/cbuild: rejected
source=no usable signature
/Users/sanmis01/Downloads/cmsis-toolbox-darwin-amd64/bin/cbuildgen: rejected
source=no usable signature
/Users/sanmis01/Downloads/cmsis-toolbox-darwin-amd64/bin/cpackget: rejected
source=no usable signature
/Users/sanmis01/Downloads/cmsis-toolbox-darwin-amd64/bin/csolution: rejected
source=no usable signature
/Users/sanmis01/Downloads/cmsis-toolbox-darwin-amd64/bin/packchk: rejected
source=no usable signature
/Users/sanmis01/Downloads/cmsis-toolbox-darwin-amd64/bin/svdconv: rejected
source=no usable signature
```

### Expected Behavior

Binaries to be notarized, like the Arm GCC releases:

```
spctl -a -vvv -t install  arm-none-eabi-objcopy
<path/to>/bin/arm-none-eabi-objcopy: accepted
source=Notarized Developer ID
origin=Developer ID Application: ARM Ltd (S345482SL3
```

### Steps To Reproduce

1. Download cmsis-toolbox-darwin-arm64.tar.gz
2. Extract cmsis-toolbox-darwin-arm64.tar.gz
3. Run `cpackget`

### Affected tools

- [X] cbuild
- [X] cbuild-gen
- [X] cpackget
- [X] csolution
- [X] packchk
- [X] svdconv

### Affected operating systems

- [ ] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [X] MacOS arm64

### Environment

- macOS 13.6.2

**Comment by brondani** [comment]
@sandeepmistry Open-CMSIS-Pack releases are not signed due to the lack of a certificate for this scope, but in the [release page](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/tag/2.2.1) you can find also the link to the "CMSIS-Toolbox Distribution by Arm" with binaries signed by Arm:
https://artifacts.keil.arm.com/cmsis-toolbox/2.2.1/
Does it help you?

**Comment by sandeepmistry** [comment]
Hi @brondani,

Thank you for the reply and pointing out the link.

The link to ""CMSIS-Toolbox Distribution by Arm" with binaries signed by Arm" was useful and I can verify that the binaries downloaded from there are notarized.
