### ISSUE TITLE
[Bug]: PACK.xsd is not the latest version

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/cmsis-toolbox#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

in toolbox 2.2.1, 1.7.28 version is present

### Expected Behavior

I would expect the latest version, so 1.7.30

### Affected tools

- [ ] cbuild
- [ ] cbuild-gen
- [ ] cpackget
- [ ] csolution
- [X] packchk
- [ ] svdconv

### Affected operating systems

- [ ] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

**Comment by jkrech** [comment]
I believe that the PACK.xsd was intentionally not updated for the patch release.
