### ISSUE TITLE
[Bug?]: Toolchain Prefix/Suffix Support

### ISSUE THREAD

**Issue by 424778940z** [Open-CMSIS-Pack/cmsis-toolbox#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Unusable feature

It cannot build the solution as it's using the wrong compiler, and there seems no way to change it

### Current Behavior

I have multiple GCC toolchains in PATH, currently there seems no way to chose between them, it always grub the gcc instaead of arm-none-eabi-gcc

### Expected Behavior

look at the cmake ext, give an option to chose what kit the user wants. or at least give a way to override in config files

### Affected tools

- [ ] cbuild
- [ ] cbuild-gen
- [ ] cpackget
- [X] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [X] Windows amd64
- [ ] Windows arm64
- [X] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

**Comment by jkrech** [comment]
CMake is offering the fallback option to pick a gcc compiler from your path. This is not recommended.
Instead please follow the instructions for [Toolchain Registration](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/installation.md#toolchain-registration)

**Comment by jkrech** [comment]
Please reopen the issue in case registering the GCC compiler using an environment variable `GCC_TOOLCHAIN_<major>_<minor>_<patch>` containing the absolute path to the `bin` directory of the GCC compiler installation does not solve the above problem.

**Comment by purdurnr** [comment]
The same situation occurred with my laptop setup.
Having several GCC compilers, the cbuild selected incorrect version.  Correcting path/environment variables resolved problem.
However, I would like to propose that a version of compiler be added to the cSolution spec.
The current spec allows user to specify/lock versions of Software Packs.
I believe it may be beneficial if user could specify/lock version of compiler that has been tested.
This will prevent a user from running with "C-Compiler" without knowing what version was used in the tested case.
This also avoids issues with Environment Variables being configured through different setup processes (NXP, ARM, IAR...)
Currently the cBuild outputs a "Warning".  Possibly update the Warning to list the suggested version from cSolution.

**Comment by jkrech** [comment]
[#1276](https://github.com/Open-CMSIS-Pack/devtools/issues/1276) is intended to ensure environment variables are configured for the toolchains being used and therefore `cbuild` becomes independent from the user's `$PATH` / `%PATH%`.
