### ISSUE TITLE
[Bug]: cbuild return exit status 0xc0000409 on windows using `cygwin`

### ISSUE THREAD

**Issue by FabKlein** [Open-CMSIS-Pack/cmsis-toolbox#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

*cbuild.exe* from a fresh install of cmsis toolbox **2.2.1** on a windows10 machine is failing with ` 0xc0000409 ` error code.

Does not appear to be related to specific project, but seeing it initially with this one:
https://github.com/FabKlein/Arm-2D/blob/cde_experiments/csolution/arm2d.csolution.yml

```
$ cbuild list contexts arm2d.csolution.yml
error cbuild: exit status 0xc0000409
```

### Expected Behavior

On Linux, I'm having the expected context list

```
>> cbuild list contexts arm2d.csolution.yml
/projects/iot/pj03124_ecps/fabkle01/git/forks/Arm-2D/csolution/arm2d_generic_bench/arm2d_generic_bench.cproject.yml:49:14 - 
arm2d_generic_bench.Release+VHT-Corstone-300
arm2d_generic_bench.Release+VHT-Corstone-300-NOLCD
arm2d_generic_bench.Release+VHT-Corstone-300-NOLCD-CDE
arm2d_generic_bench.Release+VHT-Corstone-310
arm2d_generic_bench.Release+VHT-Corstone-310-NOLCD
...
```

### Steps To Reproduce

- clone the project:
`https://github.com/FabKlein/Arm-2D`

- checkout the `cde_experiments` branch

- go into csolution folder

- install the required packs (cmsis6/cortex-dfp etc..)

- run `cbuild list contexts arm2d.csolution.yml`

### Affected tools

- [X] cbuild
- [ ] cbuild-gen
- [ ] cpackget
- [ ] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [X] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

### Environment

Windows 10 Enterprise, version 10.0.19044

**Comment by FabKlein** [comment]
few updates after debug session with @soumeh01:
- Issue might be related to *cygwin*
- cohabitation of MDK generated RTE files with cbuild (running from a cygwin terminal) is causing this 0xc0000409 issue
- starting from a fresh git cloned environment, without RTE generated content, allows the process to go further, but then it get stucks while executing following command.
`cmake -G Ninja -S "D:\projects\Arm-2D\csolution\arm2d_smartwatch_bench.Release+VHT-Corstone-300-NOLCD-AC6\intdir" -B "D:\projects\Arm-2D\csolution\arm2d_smartwatch_bench.Release+VHT-Corstone-300-NOLCD-AC6\intdir" -Wdev
`
This is using cygwin cmake / ninja
- if I do the same using windows installed cmake/ninja, the the build process go to completion

**Comment by jkrech** [comment]
@FabKlein could you please share the versions of cmake and ninja used in cygwin? Is it the same versions you are using when running using windows installed cmake/ninja:
Note: you can run `cbuild list environment` to see the cmake and ninja version being used.

**Comment by soumeh01** [comment]
```
ARM+fabkle01@S4DU2464 ~/git/fork/Arm-2D/csolution
$ cbuild list environment
CMSIS_PACK_ROOT=C:/Users/fabkle01/AppData/Local/Arm/Packs
CMSIS_COMPILER_ROOT=C:/Keil_v5/cmsis-toolbox-windows-amd64/etc
Long pathname support=enabled
cmake=C:\cygwin64\bin\cmake.exe, version 3.25.3
ninja=C:\cygwin64\bin\ninja.exe, version 1.11.1
```

**Comment by jkrech** [comment]
Nothing unusual there.

**Comment by jkrech** [comment]
We don't claim to support the cygwin environment. 
Should we make the list of supported/tested environments clearer in our documentation.
@FabKlein I hope this is not a show stopper for you. Do you have alternatives to cygwin?
Are you happy to close the issue?

**Comment by FabKlein** [comment]
This was only a sporadic window trial. Everything is OK on unix-like environments so happy to close the issue
