### ISSUE TITLE
[Question:] Cannot generate RTE file automatically

### ISSUE THREAD

**Issue by ShiinaKaze** [Open-CMSIS-Pack/cmsis-toolbox#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot generate RTE file automatically
```log
cbuild d:\Develop\Projects\VSCodeProjects\demo\demo.csolution.yml -t database --context .Debug+STM32F103C8
spawn cbuild ENOENT
cbuild d:\Develop\Projects\VSCodeProjects\demo\demo.csolution.yml -t database --context .Debug+STM32F103C8
info cbuild: Build Invocation 2.2.1 (C) 2023 Arm Ltd. and Contributors
D:/Develop/Projects/VSCodeProjects/demo/demo.cbuild-idx.yml - info csolution: file generated successfully
D:/Develop/Projects/VSCodeProjects/demo/Project/Project.Debug+STM32F103C8.cbuild.yml - info csolution: file generated successfully
D:/Develop/Projects/VSCodeProjects/demo/demo.cbuild-pack.yml - info csolution: file generated successfully
D:/Develop/Projects/VSCodeProjects/demo/Project/Project.Debug+STM32F103C8.cprj - info csolution: file generated successfully
info cbuild: Processing 1 context(s)
info cbuild: Retrieve build information for context: "Project.Debug+STM32F103C8"
================================================================
info cbuild: (1/1) Building context: "Project.Debug+STM32F103C8"

M650: Command completed successfully.


*** WARNING M634:
  File 'd:/Develop/Projects/VSCodeProjects/demo/Project/RTE/_Debug_STM32F103C8/RTE_Components.h' was not found, use the option '--update-rte' to generate it

*** ERROR M204:
  Path not found: 'd:/Develop/Projects/VSCodeProjects/demo/Project/RTE/_Debug_STM32F103C8'!
error cbuild: error executing 'cbuildgen cmake'
error cbuild: error building 'd:\Develop\Projects\VSCodeProjects\demo\Project\Project.Debug+STM32F103C8.cprj'
error cbuild: exit status 1
Process failed with exit code 4294967295
Process failed with exit code 4294967295
```

### Expected Behavior

Generating RTE file automatically.

### Steps To Reproduce

1. Create new CMSIS Solution
2. Wait for package download
3. See error and warning:
```log
*** WARNING M634:
  File 'd:/Develop/Projects/VSCodeProjects/demo/Project/RTE/_Debug_STM32F103C8/RTE_Components.h' was not found, use the option '--update-rte' to generate it

*** ERROR M204:
  Path not found: 'd:/Develop/Projects/VSCodeProjects/demo/Project/RTE/_Debug_STM32F103C8'!
```

### Affected tools

- [X] cbuild
- [X] cbuild-gen
- [ ] cpackget
- [ ] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [X] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

### Environment

Windows 11 Pro 10.0.22631 Build 22631

**Comment by jkrech** [comment]
@ShiinaKaze if I read your case correctly, you are running the CMSIS-Toolbox as part of the CMSIS csolution Visual Studio Code extension.
The output above seems to come from the process that generates the compile_commands.json.
Have you tried to run a build or update some input file e.g.  *.csolution.yml file. This should trigger a `cbuild` invocation that includes the option `--update-rte` which will ensure that the RTE folder is populated.
This is not a tools problem but something that you should report to the github repository for the Arm CMSIS csolution extension:
https://github.com/ARM-software/vscode-cmsis-csolution/issues

Note that the extension shall ensure that a project's RTE folder is up-to-date 
(e.g. run `csolution update-rte *.csolution.yml` before generating the compile_commands.json file.

**Comment by ShiinaKaze** [comment]
> @ShiinaKaze if I read your case correctly, you are running the CMSIS-Toolbox as part of the CMSIS csolution Visual Studio Code extension. The output above seems to come from the process that generates the compile_commands.json. Have you tried to run a build or update some input file e.g. *.csolution.yml file. This should trigger a `cbuild` invocation that includes the option `--update-rte` which will ensure that the RTE folder is populated. This is not a tools problem but something that you should report to the github repository for the Arm CMSIS csolution extension: https://github.com/ARM-software/vscode-cmsis-csolution/issues
> 
> Note that the extension shall ensure that a project's RTE folder is up-to-date (e.g. run `csolution update-rte *.csolution.yml` before generating the compile_commands.json file.

thanks, I will report to csolution extension.
